version: '2'

networks:
  fabric-ca:

services:
  tls-ca:
    container_name: tls-ca
    image: hyperledger/fabric-ca
    command: sh -c "fabric-ca-server start -d -b tls-ca-admin:tls-ca-adminpw --port 7052"
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=ca-tls
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ./volumes/tls/ca:/tmp/hyperledger/fabric-ca
    networks:
      - fabric-ca
    ports:
      - 7052:7052

  fed-ca:
   container_name: fed-ca
   image: hyperledger/fabric-ca
   command: sh -c "fabric-ca-server start -d -b rca-fed-admin:rca-fed-adminpw --port 7053"
   environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=rca-fed
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
   volumes:
      - ./volumes/fed/ca:/tmp/hyperledger/fabric-ca
   networks:
      - fabric-ca
   ports:
      - 7053:7053

  usp-ca:
   container_name: usp-ca
   image: hyperledger/fabric-ca
   command: /bin/bash -c 'fabric-ca-server start -d -b rca-usp-admin:rca-usp-adminpw'
   environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=rca-usp
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
   volumes:
      - ./volumes/usp/ca:/tmp/hyperledger/fabric-ca
   networks:
      - fabric-ca
   ports:
      - 7054:7054
   
  poli-usp:
   container_name: poli-usp
   image: hyperledger/fabric-peer:1.4
   environment:
      - CORE_PEER_ID=poli-usp
      - CORE_PEER_ADDRESS=poli-usp:7051
      - CORE_PEER_LOCALMSPID=uspMSP
      - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/usp/poli/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=guide_fabric-ca
      - FABRIC_LOGGING_SPEC=debug
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/usp/poli/tls-msp/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/usp/poli/tls-msp/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/usp/poli/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=amazoniaweb.duckdns.org:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
   working_dir: /opt/gopath/src/github.com/hyperledger/fabric/usp/poli
   volumes:
      - /var/run:/host/var/run
      - ./client/usp/poli:/tmp/hyperledger/usp/poli
   networks:
      - fabric-ca